"""ajustes de cuenta, documentos y saldo usado en pagos

Revision ID: 012edd3907a4
Revises: 1acd6b9f958f
Create Date: 2026-09-20 11:14:18.458660

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "012edd3907a4"
down_revision: str | Sequence[str] | None = "1acd6b9f958f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documentos",
        sa.Column("sucursal_id", sa.Uuid(), nullable=False),
        sa.Column(
            "tipo",
            sa.Enum(
                "remitos",
                "hoja_pedidos",
                "hoja_ruta",
                "tickets",
                "consolidado",
                name="tipo_documento",
            ),
            nullable=False,
        ),
        sa.Column(
            "parametros", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column(
            "estado",
            sa.Enum("pendiente", "listo", "error", name="estado_documento"),
            nullable=False,
        ),
        sa.Column("clave_storage", sa.String(length=300), nullable=True),
        sa.Column("nombre_archivo", sa.String(length=120), nullable=False),
        sa.Column("error", sa.String(length=300), nullable=True),
        sa.Column("creado_por", sa.Uuid(), nullable=False),
        sa.Column("creado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("listo_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["creado_por"], ["usuarios.id"], name=op.f("fk_documentos_creado_por_usuarios")
        ),
        sa.ForeignKeyConstraint(
            ["sucursal_id"], ["sucursales.id"], name=op.f("fk_documentos_sucursal_id_sucursales")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documentos")),
    )
    with op.batch_alter_table("documentos", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_documentos_sucursal_id"), ["sucursal_id"], unique=False
        )

    op.create_table(
        "ajustes_cuenta",
        sa.Column("sucursal_id", sa.Uuid(), nullable=False),
        sa.Column("cliente_id", sa.Uuid(), nullable=False),
        sa.Column("fecha", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "tipo",
            sa.Enum("reintegro", "repesada", "manual", "uso_saldo", name="tipo_ajuste"),
            nullable=False,
        ),
        sa.Column("importe", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("motivo", sa.String(length=200), nullable=False),
        sa.Column("referencia", sa.String(length=64), nullable=True),
        sa.Column("registrado_por", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cliente_id"], ["clientes.id"], name=op.f("fk_ajustes_cuenta_cliente_id_clientes")
        ),
        sa.ForeignKeyConstraint(
            ["registrado_por"],
            ["usuarios.id"],
            name=op.f("fk_ajustes_cuenta_registrado_por_usuarios"),
        ),
        sa.ForeignKeyConstraint(
            ["sucursal_id"],
            ["sucursales.id"],
            name=op.f("fk_ajustes_cuenta_sucursal_id_sucursales"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ajustes_cuenta")),
    )
    with op.batch_alter_table("ajustes_cuenta", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ajustes_cuenta_cliente_id"), ["cliente_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_ajustes_cuenta_fecha"), ["fecha"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_ajustes_cuenta_sucursal_id"), ["sucursal_id"], unique=False
        )

    with op.batch_alter_table("pagos", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "saldo_a_favor_usado",
                sa.Numeric(precision=12, scale=2),
                nullable=False,
                server_default="0",
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pagos", schema=None) as batch_op:
        batch_op.drop_column("saldo_a_favor_usado")

    with op.batch_alter_table("ajustes_cuenta", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ajustes_cuenta_sucursal_id"))
        batch_op.drop_index(batch_op.f("ix_ajustes_cuenta_fecha"))
        batch_op.drop_index(batch_op.f("ix_ajustes_cuenta_cliente_id"))

    op.drop_table("ajustes_cuenta")
    with op.batch_alter_table("documentos", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_documentos_sucursal_id"))

    op.drop_table("documentos")
    # ### end Alembic commands ###
