"""tokens push

Revision ID: 1acd6b9f958f
Revises: 61ba3a621ce6
Create Date: 2026-09-20 11:06:14.914644

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1acd6b9f958f"
down_revision: str | Sequence[str] | None = "61ba3a621ce6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tokens_push",
        sa.Column("usuario_id", sa.Uuid(), nullable=False),
        sa.Column("token", sa.String(length=200), nullable=False),
        sa.Column("plataforma", sa.String(length=20), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["usuario_id"], ["usuarios.id"], name=op.f("fk_tokens_push_usuario_id_usuarios")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tokens_push")),
        sa.UniqueConstraint("token", name=op.f("uq_tokens_push_token")),
    )
    with op.batch_alter_table("tokens_push", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tokens_push_usuario_id"), ["usuario_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tokens_push", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tokens_push_usuario_id"))

    op.drop_table("tokens_push")
    # ### end Alembic commands ###
