"""esquema inicial

Revision ID: 4c2d9a0b3124
Revises:
Create Date: 2026-09-19 22:01:34.767509

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4c2d9a0b3124"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("sucursal_id", sa.Uuid(), nullable=True),
        sa.Column("usuario_id", sa.Uuid(), nullable=True),
        sa.Column("accion", sa.String(length=60), nullable=False),
        sa.Column("entidad", sa.String(length=40), nullable=False),
        sa.Column("entidad_id", sa.String(length=64), nullable=False),
        sa.Column(
            "detalle", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "creado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "actualizado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_log_accion"), ["accion"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_log_entidad_id"), ["entidad_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_log_sucursal_id"), ["sucursal_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_log_usuario_id"), ["usuario_id"], unique=False)

    op.create_table(
        "contadores",
        sa.Column("nombre", sa.String(length=30), nullable=False),
        sa.Column("valor", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("nombre", name=op.f("pk_contadores")),
    )
    op.create_table(
        "productos",
        sa.Column("codigo", sa.String(length=30), nullable=False),
        sa.Column("nombre", sa.String(length=60), nullable=False),
        sa.Column("descripcion", sa.String(length=200), nullable=False),
        sa.Column("orden", sa.Integer(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "creado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "actualizado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_productos")),
        sa.UniqueConstraint("codigo", name=op.f("uq_productos_codigo")),
    )
    op.create_table(
        "sucursales",
        sa.Column("nombre", sa.String(length=80), nullable=False),
        sa.Column("direccion", sa.String(length=200), nullable=False),
        sa.Column("activa", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "creado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "actualizado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sucursales")),
        sa.UniqueConstraint("nombre", name=op.f("uq_sucursales_nombre")),
    )
    op.create_table(
        "usuarios",
        sa.Column("sucursal_id", sa.Uuid(), nullable=False),
        sa.Column("nombre", sa.String(length=100), nullable=False),
        sa.Column("usuario", sa.String(length=40), nullable=False),
        sa.Column("telefono", sa.String(length=20), nullable=True),
        sa.Column("cuit", sa.String(length=13), nullable=True),
        sa.Column("clave_hash", sa.String(length=200), nullable=False),
        sa.Column(
            "rol",
            sa.Enum("admin", "preventista", "cobrador", "cliente", name="rol"),
            nullable=False,
        ),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "creado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "actualizado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["sucursal_id"], ["sucursales.id"], name=op.f("fk_usuarios_sucursal_id_sucursales")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usuarios")),
        sa.UniqueConstraint("usuario", name=op.f("uq_usuarios_usuario")),
    )
    with op.batch_alter_table("usuarios", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_usuarios_sucursal_id"), ["sucursal_id"], unique=False)

    op.create_table(
        "vehiculos",
        sa.Column("sucursal_id", sa.Uuid(), nullable=False),
        sa.Column("nombre", sa.String(length=60), nullable=False),
        sa.Column("patente", sa.String(length=10), nullable=False),
        sa.Column("nota", sa.String(length=120), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "creado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "actualizado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["sucursal_id"], ["sucursales.id"], name=op.f("fk_vehiculos_sucursal_id_sucursales")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vehiculos")),
        sa.UniqueConstraint("patente", name=op.f("uq_vehiculos_patente")),
    )
    with op.batch_alter_table("vehiculos", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_vehiculos_sucursal_id"), ["sucursal_id"], unique=False)

    op.create_table(
        "zonas",
        sa.Column("sucursal_id", sa.Uuid(), nullable=False),
        sa.Column("nombre", sa.String(length=80), nullable=False),
        sa.Column("activa", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "creado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "actualizado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["sucursal_id"], ["sucursales.id"], name=op.f("fk_zonas_sucursal_id_sucursales")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_zonas")),
        sa.UniqueConstraint("sucursal_id", "nombre", name=op.f("uq_zonas_sucursal_id")),
    )
    with op.batch_alter_table("zonas", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_zonas_sucursal_id"), ["sucursal_id"], unique=False)

    op.create_table(
        "cierres_caja",
        sa.Column("sucursal_id", sa.Uuid(), nullable=False),
        sa.Column("usuario_id", sa.Uuid(), nullable=False),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column("efectivo_esperado", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("efectivo_recibido", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("transferencias", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("cheques", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("diferencia", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("nota", sa.String(length=300), nullable=False),
        sa.Column("cerrado_por", sa.Uuid(), nullable=False),
        sa.Column("cerrado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cerrado_por"], ["usuarios.id"], name=op.f("fk_cierres_caja_cerrado_por_usuarios")
        ),
        sa.ForeignKeyConstraint(
            ["sucursal_id"], ["sucursales.id"], name=op.f("fk_cierres_caja_sucursal_id_sucursales")
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"], ["usuarios.id"], name=op.f("fk_cierres_caja_usuario_id_usuarios")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cierres_caja")),
        sa.UniqueConstraint("usuario_id", "fecha", name=op.f("uq_cierres_caja_usuario_id")),
    )
    with op.batch_alter_table("cierres_caja", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_cierres_caja_fecha"), ["fecha"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_cierres_caja_sucursal_id"), ["sucursal_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_cierres_caja_usuario_id"), ["usuario_id"], unique=False
        )

    op.create_table(
        "clientes",
        sa.Column("sucursal_id", sa.Uuid(), nullable=False),
        sa.Column("codigo", sa.String(length=20), nullable=True),
        sa.Column("razon_social", sa.String(length=120), nullable=False),
        sa.Column("nombre_comercial", sa.String(length=120), nullable=False),
        sa.Column("cuit", sa.String(length=13), nullable=True),
        sa.Column("telefono", sa.String(length=20), nullable=True),
        sa.Column("direccion", sa.String(length=250), nullable=False),
        sa.Column("localidad", sa.String(length=80), nullable=False),
        sa.Column("lat", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("lng", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("zona_id", sa.Uuid(), nullable=True),
        sa.Column(
            "lista",
            sa.Enum("mayorista", "intermedio", "minorista", name="lista_precio"),
            nullable=False,
        ),
        sa.Column("turno", sa.Enum("manana", "tarde", name="turno"), nullable=False),
        sa.Column("preventista_id", sa.Uuid(), nullable=True),
        sa.Column("cobrador_id", sa.Uuid(), nullable=True),
        sa.Column("credito_habilitado", sa.Boolean(), nullable=False),
        sa.Column("saldo_a_favor", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("ajuste_envases", sa.Integer(), nullable=False),
        sa.Column(
            "estado_ficha",
            sa.Enum("completa", "sin_cuit", "revisar", name="estado_ficha"),
            nullable=False,
        ),
        sa.Column("observaciones", sa.String(length=500), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column(
            "datos", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "creado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "actualizado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cobrador_id"], ["usuarios.id"], name=op.f("fk_clientes_cobrador_id_usuarios")
        ),
        sa.ForeignKeyConstraint(
            ["preventista_id"], ["usuarios.id"], name=op.f("fk_clientes_preventista_id_usuarios")
        ),
        sa.ForeignKeyConstraint(
            ["sucursal_id"], ["sucursales.id"], name=op.f("fk_clientes_sucursal_id_sucursales")
        ),
        sa.ForeignKeyConstraint(["zona_id"], ["zonas.id"], name=op.f("fk_clientes_zona_id_zonas")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clientes")),
        sa.UniqueConstraint("sucursal_id", "codigo", name=op.f("uq_clientes_sucursal_id")),
        sa.UniqueConstraint("telefono", name=op.f("uq_clientes_telefono")),
    )
    with op.batch_alter_table("clientes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_clientes_cobrador_id"), ["cobrador_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_clientes_cuit"), ["cuit"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_clientes_preventista_id"), ["preventista_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_clientes_sucursal_id"), ["sucursal_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_clientes_zona_id"), ["zona_id"], unique=False)

    op.create_table(
        "listas_precio",
        sa.Column("sucursal_id", sa.Uuid(), nullable=False),
        sa.Column("producto_id", sa.Uuid(), nullable=False),
        sa.Column(
            "lista",
            sa.Enum("mayorista", "intermedio", "minorista", name="lista_precio"),
            nullable=False,
        ),
        sa.Column("turno", sa.Enum("manana", "tarde", name="turno"), nullable=False),
        sa.Column("zona_id", sa.Uuid(), nullable=True),
        sa.Column("precio", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "creado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "actualizado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["producto_id"], ["productos.id"], name=op.f("fk_listas_precio_producto_id_productos")
        ),
        sa.ForeignKeyConstraint(
            ["sucursal_id"], ["sucursales.id"], name=op.f("fk_listas_precio_sucursal_id_sucursales")
        ),
        sa.ForeignKeyConstraint(
            ["zona_id"], ["zonas.id"], name=op.f("fk_listas_precio_zona_id_zonas")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_listas_precio")),
        sa.UniqueConstraint(
            "sucursal_id",
            "producto_id",
            "lista",
            "turno",
            "zona_id",
            name=op.f("uq_listas_precio_sucursal_id"),
        ),
    )
    with op.batch_alter_table("listas_precio", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_listas_precio_sucursal_id"), ["sucursal_id"], unique=False
        )

    op.create_table(
        "mensajes",
        sa.Column("sucursal_id", sa.Uuid(), nullable=False),
        sa.Column("autor_id", sa.Uuid(), nullable=False),
        sa.Column("cuerpo", sa.Text(), nullable=False),
        sa.Column("creado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["autor_id"], ["usuarios.id"], name=op.f("fk_mensajes_autor_id_usuarios")
        ),
        sa.ForeignKeyConstraint(
            ["sucursal_id"], ["sucursales.id"], name=op.f("fk_mensajes_sucursal_id_sucursales")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mensajes")),
    )
    with op.batch_alter_table("mensajes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_mensajes_creado_en"), ["creado_en"], unique=False)
        batch_op.create_index(batch_op.f("ix_mensajes_sucursal_id"), ["sucursal_id"], unique=False)

    op.create_table(
        "noticias",
        sa.Column("sucursal_id", sa.Uuid(), nullable=False),
        sa.Column("autor_id", sa.Uuid(), nullable=False),
        sa.Column("titulo", sa.String(length=120), nullable=False),
        sa.Column("cuerpo", sa.Text(), nullable=False),
        sa.Column("fijada", sa.Boolean(), nullable=False),
        sa.Column("archivada", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "creado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "actualizado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["autor_id"], ["usuarios.id"], name=op.f("fk_noticias_autor_id_usuarios")
        ),
        sa.ForeignKeyConstraint(
            ["sucursal_id"], ["sucursales.id"], name=op.f("fk_noticias_sucursal_id_sucursales")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_noticias")),
    )
    with op.batch_alter_table("noticias", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_noticias_sucursal_id"), ["sucursal_id"], unique=False)

    op.create_table(
        "salidas",
        sa.Column("sucursal_id", sa.Uuid(), nullable=False),
        sa.Column("vehiculo_id", sa.Uuid(), nullable=False),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column("hora_salida", sa.Time(), nullable=True),
        sa.Column("preventista_id", sa.Uuid(), nullable=False),
        sa.Column("segundo_preventista_id", sa.Uuid(), nullable=True),
        sa.Column("cerrada_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("motivo_cierre", sa.String(length=200), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "creado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "actualizado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["preventista_id"], ["usuarios.id"], name=op.f("fk_salidas_preventista_id_usuarios")
        ),
        sa.ForeignKeyConstraint(
            ["segundo_preventista_id"],
            ["usuarios.id"],
            name=op.f("fk_salidas_segundo_preventista_id_usuarios"),
        ),
        sa.ForeignKeyConstraint(
            ["sucursal_id"], ["sucursales.id"], name=op.f("fk_salidas_sucursal_id_sucursales")
        ),
        sa.ForeignKeyConstraint(
            ["vehiculo_id"], ["vehiculos.id"], name=op.f("fk_salidas_vehiculo_id_vehiculos")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_salidas")),
        sa.UniqueConstraint("vehiculo_id", "fecha", name=op.f("uq_salidas_vehiculo_id")),
    )
    with op.batch_alter_table("salidas", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_salidas_fecha"), ["fecha"], unique=False)
        batch_op.create_index(batch_op.f("ix_salidas_sucursal_id"), ["sucursal_id"], unique=False)

    op.create_table(
        "sesiones_refresh",
        sa.Column("usuario_id", sa.Uuid(), nullable=False),
        sa.Column("expira_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revocado_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("creado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["usuario_id"], ["usuarios.id"], name=op.f("fk_sesiones_refresh_usuario_id_usuarios")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sesiones_refresh")),
    )
    with op.batch_alter_table("sesiones_refresh", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sesiones_refresh_usuario_id"), ["usuario_id"], unique=False
        )

    op.create_table(
        "pedidos",
        sa.Column("numero", sa.Integer(), nullable=False),
        sa.Column("sucursal_id", sa.Uuid(), nullable=False),
        sa.Column("cliente_id", sa.Uuid(), nullable=False),
        sa.Column("preventista_id", sa.Uuid(), nullable=True),
        sa.Column("segundo_preventista_id", sa.Uuid(), nullable=True),
        sa.Column("vehiculo_id", sa.Uuid(), nullable=True),
        sa.Column("salida_id", sa.Uuid(), nullable=True),
        sa.Column("zona_id", sa.Uuid(), nullable=True),
        sa.Column("turno", sa.Enum("manana", "tarde", name="turno"), nullable=False),
        sa.Column("fecha_reparto", sa.Date(), nullable=False),
        sa.Column(
            "estado",
            sa.Enum(
                "recibido",
                "preparando",
                "en_camino",
                "entregado",
                "cancelado",
                name="estado_pedido",
            ),
            nullable=False,
        ),
        sa.Column("a_cuenta", sa.Boolean(), nullable=False),
        sa.Column("pagado", sa.Boolean(), nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("estimado", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("observaciones", sa.String(length=500), nullable=False),
        sa.Column("creado_por", sa.Uuid(), nullable=True),
        sa.Column("pesado_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("entregado_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelado_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("motivo_cancelacion", sa.String(length=200), nullable=True),
        sa.Column(
            "datos", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "creado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "actualizado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cliente_id"], ["clientes.id"], name=op.f("fk_pedidos_cliente_id_clientes")
        ),
        sa.ForeignKeyConstraint(
            ["creado_por"], ["usuarios.id"], name=op.f("fk_pedidos_creado_por_usuarios")
        ),
        sa.ForeignKeyConstraint(
            ["preventista_id"], ["usuarios.id"], name=op.f("fk_pedidos_preventista_id_usuarios")
        ),
        sa.ForeignKeyConstraint(
            ["salida_id"], ["salidas.id"], name=op.f("fk_pedidos_salida_id_salidas")
        ),
        sa.ForeignKeyConstraint(
            ["segundo_preventista_id"],
            ["usuarios.id"],
            name=op.f("fk_pedidos_segundo_preventista_id_usuarios"),
        ),
        sa.ForeignKeyConstraint(
            ["sucursal_id"], ["sucursales.id"], name=op.f("fk_pedidos_sucursal_id_sucursales")
        ),
        sa.ForeignKeyConstraint(
            ["vehiculo_id"], ["vehiculos.id"], name=op.f("fk_pedidos_vehiculo_id_vehiculos")
        ),
        sa.ForeignKeyConstraint(["zona_id"], ["zonas.id"], name=op.f("fk_pedidos_zona_id_zonas")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pedidos")),
        sa.UniqueConstraint("numero", name=op.f("uq_pedidos_numero")),
    )
    with op.batch_alter_table("pedidos", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_pedidos_cliente_id"), ["cliente_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_pedidos_fecha_reparto"), ["fecha_reparto"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_pedidos_preventista_id"), ["preventista_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_pedidos_salida_id"), ["salida_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_pedidos_sucursal_id"), ["sucursal_id"], unique=False)

    op.create_table(
        "precios_cliente",
        sa.Column("cliente_id", sa.Uuid(), nullable=False),
        sa.Column("producto_id", sa.Uuid(), nullable=False),
        sa.Column("precio", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "creado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "actualizado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cliente_id"], ["clientes.id"], name=op.f("fk_precios_cliente_cliente_id_clientes")
        ),
        sa.ForeignKeyConstraint(
            ["producto_id"], ["productos.id"], name=op.f("fk_precios_cliente_producto_id_productos")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_precios_cliente")),
        sa.UniqueConstraint(
            "cliente_id", "producto_id", name=op.f("uq_precios_cliente_cliente_id")
        ),
    )
    with op.batch_alter_table("precios_cliente", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_precios_cliente_cliente_id"), ["cliente_id"], unique=False
        )

    op.create_table(
        "salida_track",
        sa.Column("salida_id", sa.Uuid(), nullable=False),
        sa.Column("lat", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("lng", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("velocidad", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("registrado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["salida_id"],
            ["salidas.id"],
            name=op.f("fk_salida_track_salida_id_salidas"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_salida_track")),
    )
    with op.batch_alter_table("salida_track", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_salida_track_registrado_en"), ["registrado_en"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_salida_track_salida_id"), ["salida_id"], unique=False)

    op.create_table(
        "cajones",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sucursal_id", sa.Uuid(), nullable=False),
        sa.Column("pedido_id", sa.Uuid(), nullable=False),
        sa.Column("producto_id", sa.Uuid(), nullable=False),
        sa.Column("bruto", sa.Numeric(precision=9, scale=3), nullable=False),
        sa.Column("tara", sa.Numeric(precision=9, scale=3), nullable=False),
        sa.Column("neto", sa.Numeric(precision=9, scale=3), nullable=False),
        sa.Column("cargado", sa.Boolean(), nullable=False),
        sa.Column("cargado_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("anulado", sa.Boolean(), nullable=False),
        sa.Column("motivo_anulacion", sa.String(length=200), nullable=True),
        sa.Column("pesado_por", sa.Uuid(), nullable=True),
        sa.Column("pesado_en", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["pedido_id"],
            ["pedidos.id"],
            name=op.f("fk_cajones_pedido_id_pedidos"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["pesado_por"], ["usuarios.id"], name=op.f("fk_cajones_pesado_por_usuarios")
        ),
        sa.ForeignKeyConstraint(
            ["producto_id"], ["productos.id"], name=op.f("fk_cajones_producto_id_productos")
        ),
        sa.ForeignKeyConstraint(
            ["sucursal_id"], ["sucursales.id"], name=op.f("fk_cajones_sucursal_id_sucursales")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cajones")),
    )
    with op.batch_alter_table("cajones", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_cajones_pedido_id"), ["pedido_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_cajones_sucursal_id"), ["sucursal_id"], unique=False)

    op.create_table(
        "movimientos_envases",
        sa.Column("sucursal_id", sa.Uuid(), nullable=False),
        sa.Column("cliente_id", sa.Uuid(), nullable=False),
        sa.Column("pedido_id", sa.Uuid(), nullable=True),
        sa.Column("fecha", sa.DateTime(timezone=True), nullable=False),
        sa.Column("dejados", sa.Integer(), nullable=False),
        sa.Column("devueltos", sa.Integer(), nullable=False),
        sa.Column("nota", sa.String(length=200), nullable=False),
        sa.Column("registrado_por", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cliente_id"], ["clientes.id"], name=op.f("fk_movimientos_envases_cliente_id_clientes")
        ),
        sa.ForeignKeyConstraint(
            ["pedido_id"], ["pedidos.id"], name=op.f("fk_movimientos_envases_pedido_id_pedidos")
        ),
        sa.ForeignKeyConstraint(
            ["registrado_por"],
            ["usuarios.id"],
            name=op.f("fk_movimientos_envases_registrado_por_usuarios"),
        ),
        sa.ForeignKeyConstraint(
            ["sucursal_id"],
            ["sucursales.id"],
            name=op.f("fk_movimientos_envases_sucursal_id_sucursales"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_movimientos_envases")),
    )
    with op.batch_alter_table("movimientos_envases", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_movimientos_envases_cliente_id"), ["cliente_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_movimientos_envases_sucursal_id"), ["sucursal_id"], unique=False
        )

    op.create_table(
        "pagos",
        sa.Column("sucursal_id", sa.Uuid(), nullable=False),
        sa.Column("cliente_id", sa.Uuid(), nullable=False),
        sa.Column("pedido_id", sa.Uuid(), nullable=True),
        sa.Column("cobrado_por", sa.Uuid(), nullable=False),
        sa.Column("fecha", sa.DateTime(timezone=True), nullable=False),
        sa.Column("total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "partes", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column(
            "pedidos_cubiertos",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            nullable=False,
        ),
        sa.Column("nota", sa.String(length=200), nullable=False),
        sa.Column("idempotencia", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "creado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "actualizado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cliente_id"], ["clientes.id"], name=op.f("fk_pagos_cliente_id_clientes")
        ),
        sa.ForeignKeyConstraint(
            ["cobrado_por"], ["usuarios.id"], name=op.f("fk_pagos_cobrado_por_usuarios")
        ),
        sa.ForeignKeyConstraint(
            ["pedido_id"], ["pedidos.id"], name=op.f("fk_pagos_pedido_id_pedidos")
        ),
        sa.ForeignKeyConstraint(
            ["sucursal_id"], ["sucursales.id"], name=op.f("fk_pagos_sucursal_id_sucursales")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pagos")),
        sa.UniqueConstraint("idempotencia", name=op.f("uq_pagos_idempotencia")),
    )
    with op.batch_alter_table("pagos", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_pagos_cliente_id"), ["cliente_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_pagos_cobrado_por"), ["cobrado_por"], unique=False)
        batch_op.create_index(batch_op.f("ix_pagos_fecha"), ["fecha"], unique=False)
        batch_op.create_index(batch_op.f("ix_pagos_pedido_id"), ["pedido_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_pagos_sucursal_id"), ["sucursal_id"], unique=False)

    op.create_table(
        "pedido_eventos",
        sa.Column("pedido_id", sa.Uuid(), nullable=False),
        sa.Column("tipo", sa.String(length=40), nullable=False),
        sa.Column(
            "detalle", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column("usuario_id", sa.Uuid(), nullable=True),
        sa.Column("creado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pedido_id"],
            ["pedidos.id"],
            name=op.f("fk_pedido_eventos_pedido_id_pedidos"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"], ["usuarios.id"], name=op.f("fk_pedido_eventos_usuario_id_usuarios")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pedido_eventos")),
    )
    with op.batch_alter_table("pedido_eventos", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_pedido_eventos_pedido_id"), ["pedido_id"], unique=False
        )

    op.create_table(
        "pedido_items",
        sa.Column("pedido_id", sa.Uuid(), nullable=False),
        sa.Column("producto_id", sa.Uuid(), nullable=False),
        sa.Column("orden", sa.Integer(), nullable=False),
        sa.Column("cajas", sa.Integer(), nullable=True),
        sa.Column("kg_pedidos", sa.Numeric(precision=9, scale=3), nullable=True),
        sa.Column("kg_pesados", sa.Numeric(precision=9, scale=3), nullable=True),
        sa.Column("precio", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("precio_propio", sa.Boolean(), nullable=False),
        sa.Column("importe", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pedido_id"],
            ["pedidos.id"],
            name=op.f("fk_pedido_items_pedido_id_pedidos"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["producto_id"], ["productos.id"], name=op.f("fk_pedido_items_producto_id_productos")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pedido_items")),
        sa.UniqueConstraint("pedido_id", "producto_id", name=op.f("uq_pedido_items_pedido_id")),
    )
    op.create_table(
        "comprobantes",
        sa.Column("sucursal_id", sa.Uuid(), nullable=False),
        sa.Column("pedido_id", sa.Uuid(), nullable=True),
        sa.Column("pago_id", sa.Uuid(), nullable=True),
        sa.Column(
            "tipo",
            sa.Enum("comprobante", "remito_firmado", name="tipo_comprobante"),
            nullable=False,
        ),
        sa.Column("clave_storage", sa.String(length=300), nullable=False),
        sa.Column("tamano_bytes", sa.Integer(), nullable=False),
        sa.Column("subido_por", sa.Uuid(), nullable=False),
        sa.Column("creado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pago_id"], ["pagos.id"], name=op.f("fk_comprobantes_pago_id_pagos")
        ),
        sa.ForeignKeyConstraint(
            ["pedido_id"], ["pedidos.id"], name=op.f("fk_comprobantes_pedido_id_pedidos")
        ),
        sa.ForeignKeyConstraint(
            ["subido_por"], ["usuarios.id"], name=op.f("fk_comprobantes_subido_por_usuarios")
        ),
        sa.ForeignKeyConstraint(
            ["sucursal_id"], ["sucursales.id"], name=op.f("fk_comprobantes_sucursal_id_sucursales")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comprobantes")),
    )
    with op.batch_alter_table("comprobantes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_comprobantes_pago_id"), ["pago_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_comprobantes_pedido_id"), ["pedido_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_comprobantes_sucursal_id"), ["sucursal_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("comprobantes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_comprobantes_sucursal_id"))
        batch_op.drop_index(batch_op.f("ix_comprobantes_pedido_id"))
        batch_op.drop_index(batch_op.f("ix_comprobantes_pago_id"))

    op.drop_table("comprobantes")
    op.drop_table("pedido_items")
    with op.batch_alter_table("pedido_eventos", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pedido_eventos_pedido_id"))

    op.drop_table("pedido_eventos")
    with op.batch_alter_table("pagos", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pagos_sucursal_id"))
        batch_op.drop_index(batch_op.f("ix_pagos_pedido_id"))
        batch_op.drop_index(batch_op.f("ix_pagos_fecha"))
        batch_op.drop_index(batch_op.f("ix_pagos_cobrado_por"))
        batch_op.drop_index(batch_op.f("ix_pagos_cliente_id"))

    op.drop_table("pagos")
    with op.batch_alter_table("movimientos_envases", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_movimientos_envases_sucursal_id"))
        batch_op.drop_index(batch_op.f("ix_movimientos_envases_cliente_id"))

    op.drop_table("movimientos_envases")
    with op.batch_alter_table("cajones", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cajones_sucursal_id"))
        batch_op.drop_index(batch_op.f("ix_cajones_pedido_id"))

    op.drop_table("cajones")
    with op.batch_alter_table("salida_track", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_salida_track_salida_id"))
        batch_op.drop_index(batch_op.f("ix_salida_track_registrado_en"))

    op.drop_table("salida_track")
    with op.batch_alter_table("precios_cliente", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_precios_cliente_cliente_id"))

    op.drop_table("precios_cliente")
    with op.batch_alter_table("pedidos", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pedidos_sucursal_id"))
        batch_op.drop_index(batch_op.f("ix_pedidos_salida_id"))
        batch_op.drop_index(batch_op.f("ix_pedidos_preventista_id"))
        batch_op.drop_index(batch_op.f("ix_pedidos_fecha_reparto"))
        batch_op.drop_index(batch_op.f("ix_pedidos_cliente_id"))

    op.drop_table("pedidos")
    with op.batch_alter_table("sesiones_refresh", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sesiones_refresh_usuario_id"))

    op.drop_table("sesiones_refresh")
    with op.batch_alter_table("salidas", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_salidas_sucursal_id"))
        batch_op.drop_index(batch_op.f("ix_salidas_fecha"))

    op.drop_table("salidas")
    with op.batch_alter_table("noticias", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_noticias_sucursal_id"))

    op.drop_table("noticias")
    with op.batch_alter_table("mensajes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_mensajes_sucursal_id"))
        batch_op.drop_index(batch_op.f("ix_mensajes_creado_en"))

    op.drop_table("mensajes")
    with op.batch_alter_table("listas_precio", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_listas_precio_sucursal_id"))

    op.drop_table("listas_precio")
    with op.batch_alter_table("clientes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_clientes_zona_id"))
        batch_op.drop_index(batch_op.f("ix_clientes_sucursal_id"))
        batch_op.drop_index(batch_op.f("ix_clientes_preventista_id"))
        batch_op.drop_index(batch_op.f("ix_clientes_cuit"))
        batch_op.drop_index(batch_op.f("ix_clientes_cobrador_id"))

    op.drop_table("clientes")
    with op.batch_alter_table("cierres_caja", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cierres_caja_usuario_id"))
        batch_op.drop_index(batch_op.f("ix_cierres_caja_sucursal_id"))
        batch_op.drop_index(batch_op.f("ix_cierres_caja_fecha"))

    op.drop_table("cierres_caja")
    with op.batch_alter_table("zonas", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_zonas_sucursal_id"))

    op.drop_table("zonas")
    with op.batch_alter_table("vehiculos", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_vehiculos_sucursal_id"))

    op.drop_table("vehiculos")
    with op.batch_alter_table("usuarios", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_usuarios_sucursal_id"))

    op.drop_table("usuarios")
    op.drop_table("sucursales")
    op.drop_table("productos")
    op.drop_table("contadores")
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_log_usuario_id"))
        batch_op.drop_index(batch_op.f("ix_audit_log_sucursal_id"))
        batch_op.drop_index(batch_op.f("ix_audit_log_entidad_id"))
        batch_op.drop_index(batch_op.f("ix_audit_log_accion"))

    op.drop_table("audit_log")
    # ### end Alembic commands ###
