"""tara por sucursal

Revision ID: 61ba3a621ce6
Revises: 4c2d9a0b3124
Create Date: 2026-09-20 10:35:12.869569

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "61ba3a621ce6"
down_revision: str | Sequence[str] | None = "4c2d9a0b3124"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sucursales", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "tara", sa.Numeric(precision=9, scale=3), nullable=False, server_default="1.700"
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sucursales", schema=None) as batch_op:
        batch_op.drop_column("tara")

    # ### end Alembic commands ###
