"""sin_coordenadas_ni_gps

Revision ID: dc13e1927526
Revises: 012edd3907a4
Create Date: 2026-09-21 18:04:24.969236

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dc13e1927526"
down_revision: str | Sequence[str] | None = "012edd3907a4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_salida_track_registrado_en"), table_name="salida_track")
    op.drop_index(op.f("ix_salida_track_salida_id"), table_name="salida_track")
    op.drop_table("salida_track")
    op.drop_column("clientes", "lng")
    op.drop_column("clientes", "lat")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clientes",
        sa.Column("lat", sa.NUMERIC(precision=9, scale=6), autoincrement=False, nullable=True),
    )
    op.add_column(
        "clientes",
        sa.Column("lng", sa.NUMERIC(precision=9, scale=6), autoincrement=False, nullable=True),
    )
    op.create_table(
        "salida_track",
        sa.Column("salida_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("lat", sa.NUMERIC(precision=9, scale=6), autoincrement=False, nullable=False),
        sa.Column("lng", sa.NUMERIC(precision=9, scale=6), autoincrement=False, nullable=False),
        sa.Column(
            "velocidad", sa.NUMERIC(precision=9, scale=6), autoincrement=False, nullable=True
        ),
        sa.Column(
            "registrado_en",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["salida_id"],
            ["salidas.id"],
            name=op.f("fk_salida_track_salida_id_salidas"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_salida_track")),
    )
    op.create_index(op.f("ix_salida_track_salida_id"), "salida_track", ["salida_id"], unique=False)
    op.create_index(
        op.f("ix_salida_track_registrado_en"), "salida_track", ["registrado_en"], unique=False
    )
    # ### end Alembic commands ###
